### ISSUE TITLE
Improved editing of empty secrets

### ISSUE THREAD

**Issue by dcarley** [rajatjindal/kubectl-modify-secret#11]
If you create an empty secret and then use `modify-secret` to add data to it, you get presented with an empty JSON document, which is confusing if you were expecting to write YAML:
```
$ kubectl create secret generic dcarley
secret/dcarley created
$ EDITOR=cat kubectl modify-secret dcarley
{}
INFO[0000] no changes done to secret "dcarley"
```

This seems to be a "feature" of the YAML library when you marshal an empty map:

- https://play.golang.org/p/9Byzr0yfQD3

What do you think about detecting this and presenting a completely empty document instead?

**Comment by dcarley** [comment]
Additionally creating the empty secret, without requiring a separate command, would also be nice 🤔

**Comment by rajatjindal** [comment]
hey @dcarley 

thanks a lot for reporting this. 

I think the first one definitely makes sense, i will submit fix for that soon. (PR welcome too)

for the second one, creation of secret is more involved command (e.g. generic vs tls etc). and then they have more flags etc. 

In my opinion that would be out of scope for this tool. what do you think?

**Comment by dcarley** [comment]
> In my opinion that would be out of scope for this tool. what do you think?

Yeah, that makes sense 👍 

I've raised #12 for the first change.
