### ISSUE TITLE
Use "KUBE_EDITOR" instead of "EDITOR"

### ISSUE THREAD

**Issue by jose-rojas0** [rajatjindal/kubectl-modify-secret#14]
`kubectl` supports using the `KUBE_EDITOR` env var for setting the editor to use for `kubectl` commands, as a `kubectl` plugin it feels appropriate to have `kubectl-modify-secret` check that env variable first, then check `EDITOR`, and lastly default to `vi` (as it does right now).

I'd be ok putting up a PR for this if the proposal sounds reasonable.

**Comment by rajatjindal** [comment]
fixed with #15
