### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by Bonehead5338** [rajatjindal/kubectl-modify-secret#16]
Hi,

I noticed I got:  `failed to install plugin "modify-secret": plugin "modify-secret" does not offer installation for this platform` when trying to install via krew. Also noticed that the windows line was commented out in build.sh. Is it possible to get this for Windows?

Thanks

**Comment by rajatjindal** [comment]
yes absolutely, i dont see a reason why not. would you be willing to submit a PR for this?

**Comment by Bonehead5338** [comment]
Sure, I will have a look this evening

**Comment by apetrichkovich** [comment]
Hello.
Still not working.
Any news?

**Comment by rajatjindal** [comment]
once this pr is accepted, windows version should be available. https://github.com/kubernetes-sigs/krew-index/pull/3363/files

**Comment by rajatjindal** [comment]
this is now done
