### ISSUE TITLE
error: unknown command "modify-secret" for "kubectl"

### ISSUE THREAD

**Issue by daniel-dodoo** [rajatjindal/kubectl-modify-secret#22]
I want to install kubectl-modify-secret to my Ubuntu 20.04.3 LTS @rajatjindal 

I downloaded the archive file from releases, https://github.com/rajatjindal/kubectl-modify-secret/releases/download/v0.0.43/kubectl-modify-secret_v0.0.43_linux_amd64.tar.gz

Extracted tile file and move /usr/local/bin

and I have the following error when I confirm the installation

kubectl modify-secret --help

``error: unknown command "modify-secret" for "kubectl"``

**Comment by rajatjindal** [comment]
is the `kubectl` an alias or a function? I have seen this happening in that case.

**Comment by rajatjindal** [comment]
with help from a community member, I was finally able to understand the root cause and fixed it with release v0.0.46

thanks
