### ISSUE TITLE
Feature request: installable via homebrew.

### ISSUE THREAD

**Issue by guettli** [rajatjindal/kubectl-modify-secret#31]
I use homebrew for almost all software. It is supported by all major platforms: Linux, Mac and WSL.

It would be great if I could install modify-secret via homebrew.

Thank you for this tool, it is really handy.

**Comment by rajatjindal** [comment]
Hi @guettli , I am glad to hear you are finding this useful 🎉 . 

I gave a shot at setting up tap for it, could you please try and let me know if it works for you:

```
brew install rajatjindal/tap    
brew install rajatjindal/tap/modify-secret 

kubectl-modify-secret -h
```

**Comment by guettli** [comment]
The first command was not needed, this works, too:

```
brew install rajatjindal/tap/modify-secret 
```


`kubectl-modify-secret -h` works.

But this does not:

````
❯ kubectl modify-secret   
error: unknown command "modify-secret" for "kubectl"
```

It seems that an underscore is needed for above usage:

https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#names-with-dashes-and-underscores

Or you use one work: to avoid the dash-vs-underscore: If you call it modifysecret, then `kubectl modifysecret` should work.

What do you think about that?

I don't have a real problem with that. I can use `kubectl-modify-secret`, too.

**Comment by rajatjindal** [comment]
oh wow, TIL about underscores and dash in kubectl plugin. that sounds so confusing and complicated. wondering when that was introduced (or I completely missed it to start with).

that might also explain issues like #22 

Let me think a little more about it and get back here.

**Comment by guettli** [comment]
BTW, I am still  learning, too.

I started a thread at reddit, becaues I don't understand why `krew` exists at all:

https://www.reddit.com/r/kubernetes/comments/194rre7/why_use_krew_kubectl_plugins/

I think distributing via brew is better, since you can get autocomplete working without extending the bashrc file for every tool.

If you install via brew, then the tool can use the brew-way to install autocomplete.

I think even in the context of kubernetes there are more people who have brew installed, compared to krew.

**Comment by rajatjindal** [comment]
thank you for pointing me out to the documentation. I've now fixed the binary to follow the format suggested by kubectl, and installing via brew should work as well. 

the binary name is now: `kubectl-modify_secret` and you should be able to use it as "kubectl modify-secret -h" as well.

thanks again
