### ISSUE TITLE
Add YAML syntax highlight in the editor

### ISSUE THREAD

**Issue by gdubicki** [rajatjindal/kubectl-modify-secret#32]
Hi! Thanks for the plugin, @rajatjindal, it does the job really well! 😊 👍 

But it would be even better if the decoded file would be open with a syntax highlight in the editor.

In the case of my `vim`, but probably other editors will work the same, it should be enough to add `.yaml` extension to the temporary file.

**Comment by rajatjindal** [comment]
great suggestion 👍 and thank you for your kind words. 

I've published v0.0.47 with this change.
