### ISSUE TITLE
Helm support

### ISSUE THREAD

**Issue by ArnaudTA** [rajatjindal/kubectl-modify-secret#36]
Hi Rajat, first of all thanks for your plugin !

I forked your project to manipulate helm secrets double base64 + gzip compression.

Would you like to support this feature in your plugin, or would you prefer that I maintain my own plugin?

Are you okay with the fact I totally stole your code to make mine ?

**Comment by rajatjindal** [comment]
Hi @ArnaudTA 

Have you seen https://github.com/rajatjindal/helm-updaterelease which do exactly this?

**Comment by ArnaudTA** [comment]
I didn't saw it but it works well, not an editor as I initially wanted but the Helm package functions are easy to understand and less painful. I star it, thank you !

**Comment by rajatjindal** [comment]
having said that, if you still want to reuse some part (or all of it) code from this repo, please feel free to do so.
