### ISSUE TITLE
Error: no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by darkzhadow** [rajatjindal/kubectl-modify-secret#7]
It has an error when using a GKE (Google Kubernetes Engine) Cluster

Error: no Auth Provider found for name "gcp"

**Comment by rajatjindal** [comment]
apologies for replying so late on this issue, missed it somehow.

hmm, I thought I had tried this with gcp. I'll try to reproduce later today, and will try to submit a fix.

(btw PR are welcome if you are able to fix this).

**Comment by rajatjindal** [comment]
@darkzhadow this should be fixed now. Please reopen if this issue still persists.
